version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: little-alchemy-backend
    ports:
      - "8080:8080"
    volumes:
      - recipe-data:/root/data
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: little-alchemy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # URL untuk API
      - NEXT_PUBLIC_API_URL=http://backend:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  recipe-data:
    # volume untuk menyimpan data recipe hasil scraping